In [ ]:
import torch

**Tensors**
- PyTorch is a library for processing tensors
- Tensor is a general version of number/vector/matrix/n-dimensional array

In [ ]:
# 4. is short for 4.0, tells python and pytorch to create a floating point numbe
t1 = torch.tensor(4.)
t1

tensor(4.)

In [ ]:
# check type of tensor
t1.dtype

torch.float32

In [ ]:
# vector
t2 = torch.tensor([1., 2, 3, 4])
# all elements of tensor must have same data type, so 1. causes all elements
# to be floating point
t2

tensor([1., 2., 3., 4.])

In [ ]:
# matrix
t3 = torch.tensor([[5., 6],
                  [7, 8],
                  [9, 10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [ ]:
# 3d tensor
t4 = torch.tensor([
    [[11, 12, 13],
     [13, 14, 15]],
    [[15, 16, 17],
     [17, 18, 19]]])
# shape must be regular - all lists in a given dimension must have same length
t4

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])

In [ ]:
# tensors can have any number of dimensions and lengths along each dimension
# .shape gives length along each dimension

print(t1) # scalar
t1.shape

tensor(4.)


torch.Size([])

In [ ]:
print(t2) # vector
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [ ]:
print(t3) # matrix
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [ ]:
print(t4) # 3d
t4.shape

tensor([[[11, 12, 13],
         [13, 14, 15]],

        [[15, 16, 17],
         [17, 18, 19]]])


torch.Size([2, 2, 3])

**Tensor operations and gradients**

In [ ]:
# can combine tensors with arithmetic operators
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
x,w,b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

In [ ]:
# arithmetic operations as if w,x,b were regular numbers
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [ ]:
# pytorch can automatically compute derivatives of tensors

# .backward() calculates derivative of y w.r.t tensors w/ requires_grad=True
y.backward()

# derivatives of y are stored in .grad property of the respective tensors
print('dy/dx:', x.grad) # dy/dx = None - x doesn't have requires_grad=True
print('dy/dw:', w.grad) # dy/dw = x = 3
print('dy/db:', b.grad) # dy/db = 1

# .grad stands for gradient (as in derivative)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


**Interoperability with Numpy**
- Popular open source library for math and science
- Efficient operations on large multi-dimensional arrays
- Large ecosystem of supporting libraries:
  - Matplotlib - plotting and visualization
  - OpenCV - image/video processing
  - Pandas - file I/O, data analysis
- PyTorch interoperates w/ Numpy

In [ ]:
import numpy as np

In [ ]:
# create array in numpy
x = np.array([[1, 2], 
              [3, 4.]])
# notice that once again, all data types must be the same
# the 4. causes all entries to be converted to floating point
x

array([[1., 2.],
       [3., 4.]])

In [ ]:
# convert numpy array to pytorch tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
# convert pytorch tensor to numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])